apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers: 
  - name: helloworld
    image: soumyadeep90014842/helloworld:1.0.0
    ports:
    - containerPort: 8081